### ISSUE TITLE
running main.cpp?

### ISSUE THREAD

**Issue by kevin-j-wang** [karansher/computer-graphics-raster-images#16]
Is running main.cpp without editing any files supposed to give 11 errors that are all in 'xutility'? Am I supposed to only run raster.exe?

**Comment by abhimadan** [comment]
No, it isn't supposed to produce any errors. How did you set up your project?

**Comment by kevin-j-wang** [comment]
nvm, i restarted from scratch and it works. there are like 50 warnings though, but ill assume those are normal
