### ISSUE TITLE
about vector size in simulate_bayer_mosaic

### ISSUE THREAD

**Issue by cuiboyuan** [karansher/computer-graphics-raster-images#19]
Here at line 9 of `simulate_bayer_mosaic.cpp`:
https://github.com/karansher/computer-graphics-raster-images/blob/df193e7110558591b685a89cac1054ef9591c15a/src/simulate_bayer_mosaic.cpp#L9

The vector size is resized to `width*height`. Why is it not `width*height*3` as the README mentions that "The output image should be the same size as the input"?

Thanks

**Comment by abhimadan** [comment]
A bayer mosaic has only one colour channel. So the _images_ are the same size but the _buffers_ (arrays that store the images) are not.

**Comment by cuiboyuan** [comment]
ok I see. Thanks!
