### ISSUE TITLE
Visual Studio Problem

### ISSUE THREAD

**Issue by JanardanS** [karansher/computer-graphics-raster-images#2]
I downloaded Visual Studio 2022 edition, and I also have cmake and C++ compiler installed, the latest ones, but when running cmake .., it uses visual studios C++ compiler, and that compiler doesn't seem to properly create the executable. What should I do to fix this issue?

**Comment by abhimadan** [comment]
Running `cmake ..` only creates the Visual Studio project, and does not build the executable. You have to open the created .sln file in Visual Studio and compile it from there.

**Comment by JanardanS** [comment]
The problem is I dont actually see the .sln file, unless its a hidden file?

**Comment by abhimadan** [comment]
It's not a hidden file. Can you provide more details about your issue? What was printed in your terminal when you ran `cmake ..`?

**Comment by JanardanS** [comment]
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Failed
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Failed
-- The compiler C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe has no C++11 support. Please use a different C++ compiler.

**Comment by abhimadan** [comment]
Looks like your installation is missing some pieces. Did you install the latest Windows 10/11 SDK? You can reopen the installer and install the missing components. I believe selecting the "Desktop Development with C++" workload in the installer, as described in the readme, should include it, but if not, you can directly select the SDK in the installer window.

**Comment by JanardanS** [comment]
I have Windows 11 SDK (10.0.22621.0) installed, yet it still produces the same error in my terminal.

**Comment by abhimadan** [comment]
Hmm, try deleting your `build` directory, then recreate it and re-run `cmake ..` inside that folder. There might be some cached information that is causing cmake to fail.

**Comment by JanardanS** [comment]
It is still giving me the same issues, is it possible to come tmrw to fix this problem? I am not sure exactly why this is occurring.

**Comment by abhimadan** [comment]
Sure, please attend the 11am tutorial tomorrow and I'll be happy to help you.

**Comment by abhimadan** [comment]
One last thing to try: in the file `CMakeLists.txt` on line 8, change "-std=c++11" to "-std=c++14", since apparently newer versions of Visual Studio no longer support flags for older C++ versions. Please let me know if that works so I can update the cmake file in the repo; if not, we'll figure it out tomorrow.

**Comment by InesBosch** [comment]
I'm having the same issue as here https://github.com/karansher/computer-graphics-raster-images/issues/2#issuecomment-1245805167 but I have the raster.sln file and my code compiles, any idea of what is going on? Thanks!!

**Comment by abhimadan** [comment]
My suspicion is that the test in `CMakeLists.txt` for checking C++ version support doesn't work on Windows, but the latest Visual Studio supports the required C++ version. If you're able to skip that check and proceed with the rest of the generation process, you should get a working .sln file. If it works and you can compile your code, there's nothing to worry about.

**Comment by JanardanS** [comment]
I tried with C++14, still not working properly, and I tried to skip that check by commenting it out, yet it still doesn't create the executables. Should I also do set(CMAKE_CXX_FLAGS), and if so, what would I set it to, std=c++20?

There's also this message, where it says check for working C/CXX compiler: "visual studios compiler path" - skipped, before it gets to the checks, maybe that's the reason?

**Comment by abhimadan** [comment]
CMake caches a variety of information after each execution, so if you've changed anything in your config file `CMakeLists.txt`, you have to delete `CMakeCache.txt` in the `build` folder, or delete the entire folder and remake it. CMake skipping checks is a good example of it relying on cached information, so it's probably not reading your updated file correctly.

**Comment by JanardanS** [comment]
Even after deleting the CMakeCache.txt in the build folder, it still says skip. Does this have to do with the fact I am using windows 11?

**Comment by Tahmeem** [comment]
I got this https://github.com/karansher/computer-graphics-raster-images/issues/2#issuecomment-1245805167 but was able to get a solutions file. When i try to build it in Visual studio i get this 
![image](https://user-images.githubusercontent.com/45083175/190019387-64ecb24b-16cd-49fe-ae23-22354628894b.png)

**Comment by Tahmeem** [comment]
> Even after deleting the CMakeCache.txt in the build folder, it still says skip. Does this have to do with the fact I am using windows 11?

Im using windows 10 i dont think that matters.

**Comment by abhimadan** [comment]
@JanardanS, it's not a huge deal if it skips that step even without a cache file - what matters is if it correctly generates a .sln file.

@Tahmeem, you need to change the startup project to `raster` [(see here for instructions on how to do this)](https://stackoverflow.com/questions/12833074/how-do-i-switch-between-or-highlight-projects-of-the-same-solution-in-visual-s). `ALL_BUILD` is a dummy target that compiles everything else in the .sln file but can't be run directly.

**Comment by Tahmeem** [comment]
> @JanardanS, it's not a huge deal if it skips that step even without a cache file - what matters is if it correctly generates a .sln file.
> 
> @Tahmeem, you need to change the startup project to `raster` [(see here for instructions on how to do this)](https://stackoverflow.com/questions/12833074/how-do-i-switch-between-or-highlight-projects-of-the-same-solution-in-visual-s). `ALL_BUILD` is a dummy target that compiles everything else in the .sln file but can't be run directly.

Thanks

**Comment by JanardanS** [comment]
It produces an sln file, but that sln file is hidden by default, and isn't in any folder like debug which should occur for visual studio. Is that fine? I can build it, and execute that sln file.

**Comment by abhimadan** [comment]
You should find a file called `raster.sln` in the `build` folder - the debug and release folders contain exe files after you've compiled them in Visual Studio. Can you please explain what you mean by the file being hidden by default?

**Comment by JanardanS** [comment]
My build file without showing any hidden files gives me an empty folder. After clicking on Show all Files for visual studios, i get this

![image](https://user-images.githubusercontent.com/35342648/190030311-4c07fe1f-ef79-48dd-aa3c-cdfd82fceda3.png)

Is this what your suppose to see?

**Comment by abhimadan** [comment]
Ah, ok. I wouldn't call the sln file hidden, it's just that (I think) Visual Studio only shows source files in that view. I was actually asking about whether you could find it in the file explorer or when starting up Visual Studio and looking for sln files to open through the startup window. So overall this all looks like expected behaviour.

**Comment by JanardanS** [comment]
Oh I see now, I thought VS show all files will show hidden files, but it's not hidden like you said. Thank you so much for helping me with this confusion.
