### ISSUE TITLE
Xcode does not open project

### ISSUE THREAD

**Issue by rainyu7246** [karansher/computer-graphics-raster-images#22]
Hi, I'm trying to set up Lab1 by cloning the git repository and opening it in Xcode. However, it does not let me open it. I'm using a Macbook air with an M1 chip. Can I get some help on that? I also wonder why we are suggested to use Xcode instead of VScode on mac?

**Comment by HELENCUICUI** [comment]
I have the same issue with Xcode. Can someone please help?

**Comment by abhimadan** [comment]
You don't have to use the XCode IDE, but you do need to install it to access its command line tools like the compiler. CMake generates a Makefile, so you can use whatever text editor you want and simply call `make` from the command line.

**Comment by HELENCUICUI** [comment]
So for mac users, Is it better to use Xcode or VScode for future assignments?

**Comment by abhimadan** [comment]
There's a difference between a text editor and a compiler. We specify which _compiler_ you use (the one installed via xcode), but we don't care which _text editor_ you use, so feel free to use VSCode. It's important to keep in mind that VSCode is just a text editor and doesn't include a compiler.

**Comment by HELENCUICUI** [comment]
ok! Thank you! Also How do I fix the Xcode can't open the project issue?

**Comment by abhimadan** [comment]
There's no issue here. Xcode uses its own project files, which CMake didn't generate in this case since it produced a Makefile. You can provide an additional argument to CMake to produce an xcode project if you prefer, but IMO it's easier to use makefiles.

**Comment by rainyu7246** [comment]
I see. Thank you very much!
