### ISSUE TITLE
Problems when executing cmake

### ISSUE THREAD

**Issue by Ming-Yeung-Alfred-Meng** [karansher/computer-graphics-raster-images#26]
![image](https://user-images.githubusercontent.com/81248498/190443409-d52e0717-5a98-432b-9079-49a7d1d14311.png)

I am on Windows 11 and VS 2022. The messages from cmake told me to use a compiler with support for c++11. Is this something that I should worry about?

After building the sln file and running the exe file, I did not get any output file, but I guess this is normal since I have to started working on the implementations yet. Please confirm for me.

**Comment by abhimadan** [comment]
You already have support for C++11, but the check in the cmake file doesn't work for newer versions of Visual Studio. Don't worry about it.

**Comment by Ming-Yeung-Alfred-Meng** [comment]
Thank you.
