### ISSUE TITLE
What would be the best way to create helper functions that are shared between files?

### ISSUE THREAD

**Issue by andyw1589** [karansher/computer-graphics-raster-images#27]
I know I can create a helper function within a cpp file, but how would I use that same function in another cpp file if we're not allowed to create new headers?

**Comment by abhimadan** [comment]
You shouldn't need to do this, but if you really want to use the same function in multiple files, you will need to duplicate the function in each cpp file that needs it, defining it in an anonymous namespace so you don't get linker errors.
