### ISSUE TITLE
Default background colour for rgba_to_rgb?

### ISSUE THREAD

**Issue by armst297** [karansher/computer-graphics-raster-images#31]
The calculation to get an RBG value from an RGBA value is based on a foreground and background colour, what is the "background" colour we are supposed to be using for our image? e.g. white, black. OR is the format of the RGBA that we have been given include information for the background?

**Comment by abhimadan** [comment]
There's no calculation involved - you just drop the alpha channel. The alpha value is only really used when you stack images on top of each other using the Porter-Duff operator. (Technically you also use it when generating premultiplied alpha images, but we aren't doing that in this assignment.)

**Comment by armst297** [comment]
Thank you for the clarification!
