### ISSUE TITLE
grayscale write_ppm.cpp

### ISSUE THREAD

**Issue by ttyhhu** [karansher/computer-graphics-raster-images#32]
For grayscale picture, since the filename indicated that it is a ppm file (which requires 3 color channel values) instead of a pgm file (which only requires one), should we just write it like a color RGB image with the same intensity in every channel?

**Comment by abhimadan** [comment]
Yes

**Comment by cuiboyuan** [comment]
Will we get marks off for writing grayscale images as PGM files? (i.e., writing P2 header instead of P3 in `write_ppm.cpp` for grayscale images but keeping the .ppm extension)

**Comment by abhimadan** [comment]
Yes, it's fine to use P2 in that case

**Comment by guyuli2002** [comment]
My output is gray.ppm file, I can only open it by pgm viewer if I change .ppm to .pgm. Is that ok?
