### ISSUE TITLE
clang:error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by rainyu7246** [karansher/computer-graphics-raster-images#34]
<img width="642" alt="Screen Shot 2022-09-15 at 9 21 23 PM" src="https://user-images.githubusercontent.com/103672387/190536270-84a77535-136a-4b46-b946-5650727efbcd.png">
<img width="632" alt="Screen Shot 2022-09-15 at 9 21 38 PM" src="https://user-images.githubusercontent.com/103672387/190536276-6eeee837-be89-4b00-b5ac-559859c0430b.png">

Hi, I tried to compile my code but it's showing this error and I don't know how to solve it. Can someone please help? Thank you:(

**Comment by abhimadan** [comment]
It's trying to compile `rgba_to_rgb` as an executable, but it fails because it doesn't have a `main` function defined in it. You just need to run `make`, which compiles a single executable `raster` that runs all the functions in this assignment.

**Comment by rainyu7246** [comment]
ok thank you!
