### ISSUE TITLE
resolved - cmake pathing issue

### ISSUE THREAD

**Issue by taiti22** [karansher/computer-graphics-raster-images#41]
I downloaded Visual Studio using the provided instructions (including the 'Desktop Development with C++', but I think there is some sort of pathing issue for cmake? I am getting this error when I run cmake from the build directory in my assignment folder:

"'cmake' is not recognized as an internal or external command,
operable program or batch file."

I just uninstalled and re-installed Visual Studio with desktop development, and double checked that the "Visual C++ Tools for CMake" would be installed, but I'm getting the same error.

**Comment by abhimadan** [comment]
You need to download cmake as well, from their website https://cmake.org/download/. Visual Studio provides information for cmake to generate sln files, but doesn't provide a separate executable for cmake.

**Comment by taiti22** [comment]
Oh thank you, I thought it was included in the desktop development!
