### ISSUE TITLE
Debugging for Mac arm 

### ISSUE THREAD

**Issue by iiiizuo** [karansher/computer-graphics-raster-images#45]
Hi,
I'm wondering how should I debug for future labs on mac as I'm using vscode text editor and cmake to compile. I run the code using the raster executable generated by the make command. I saw that windows users can use vscode ide's debugger. If i want to stick with vscode text editor, is there a way to use the debugger? If not, should i download the real vscode ide? Thanks.

**Comment by abhimadan** [comment]
You can use `lldb`, a command line debugger. It looks ugly but it has the same features as the Visual Studio debugger on Windows. Alternatively, if you're using VSCode, you can install a C++ plugin that provides nice features, including a wrapper for lldb: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

**Comment by iiiizuo** [comment]
Thank you!

**Comment by iiiizuo** [comment]
Hi
I tried the debugger with some modifications to the tasks.json (image 1), but it returned with the following error when i tried to debug the main.cpp. I'm not sure why this happened. Thank you!
<img width="520" alt="Screen Shot 2022-09-17 at 9 32 14 PM" src="https://user-images.githubusercontent.com/97774250/190882599-679d4473-7936-450a-9416-3df8488b1310.png">

<img width="949" alt="image" src="https://user-images.githubusercontent.com/97774250/190882622-9834485d-eb36-4734-821f-2de742bc80b4.png">
