### ISSUE TITLE
desaturated output looks different

### ISSUE THREAD

**Issue by YuChinKoo** [karansher/computer-graphics-raster-images#47]
After implementing desaturated function, I get this output:

<img width="393" alt="Screen Shot 2022-09-17 at 9 43 48 PM" src="https://user-images.githubusercontent.com/45642598/190882036-cdee52ed-afc5-4ff7-a3c8-76b8f5f0743d.png">

However, this image looks a lot lighter than the one shown in the handout

I was wondering if you guys used a smaller factor for desaturating the image, or do i have a bug in my implementation

**Comment by abhimadan** [comment]
You probably have a bug. One potential bug that's very easy to run into is accidentally doing integer division instead of float division.
