### ISSUE TITLE
Are we allowed to write code outside the commented area?

### ISSUE THREAD

**Issue by Tian99Yu** [karansher/computer-graphics-raster-images#48]
For example, in the below screenshot, are we only allowed to write code between line 10 and 12 ? 

Can we add some helper functions outside the provided code in the same file?

 And will removing line 10 and 12 results in any errors during Markus evaluation?

<img width="657" alt="Screen Shot 2022-09-18 at 12 50 40 AM" src="https://user-images.githubusercontent.com/59063570/190886314-b23a0600-b4b6-4e58-9736-dd46e0ff6d94.png">

**Comment by abhimadan** [comment]
Yes, as mentioned in the FAQ, helper functions are allowed.
