### ISSUE TITLE
rgba to rgb; are we supposed to apply transparency?

### ISSUE THREAD

**Issue by andyw1589** [karansher/computer-graphics-raster-images#5]
Do we directly extract the RGB values, or do we have to apply transparency first? for example, if you have (r, g, b, a) = (1, 1, 1, 0.5), do we return (r, g, b) = (1, 1, 1) or (0.5, 0.5, 0.5)?

**Comment by abhimadan** [comment]
You only apply transparency to the RGB channels when you stack images on top of each other with the Porter-Duff operator, not when you drop the alpha channel.
