### ISSUE TITLE
Compilation issues, not sure if the steps Im following are correct?

### ISSUE THREAD

**Issue by MicheleMassa802** [karansher/computer-graphics-raster-images#51]
I have completed all my .cpp files (completed my solutions), but I have never been able to test them because I cannot seem to compile the project (I have probably spent longer trying to get this project to compile than writing code). The steps I follow are (from my project folder where main.cpp is found):

- mkdir build
- cd build
- cmake .. → this raises the Compile has no C++11 support message but it produces a raster.sln file, so from other posts Ive read here, that should be fine
- Go to Visual Studio→ Open a project / solution option → open the generated raster.sln file inside projectDir/build
- Here is VS my Solution Configuration is “Debug” and my Solution Platform is “x64”
- I go to build → build solution and in the console I get the output:

Build started...
1>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
1>Project not selected to build for this solution configuration
========== Build: 0 succeeded, 0 failed, 2 up-to-date, 1 skipped ==========

- So from there my intuition is to go back to build and select: Build ALL_BUILD, from which I get:

Build started...
========== Build: 0 succeeded, 0 failed, 3 up-to-date, 0 skipped ==========

- At this point that the project should be built from what I understand, I click the green arrow (local windows debugger)
- But this results in a warning: Unable to start program ‘C:\Users\miche\…\asnFolder\build\x64\Debug\ALL_BUILD’ Access is denied
- And in the end, nothing really happens. After using VS I get a Debug folder inside build, and within debug there is a raster.exe file
- I have tried running ./Debug/raster but this results in another error and no output images
- 
So I have a couple questions (I really wanted to wait until a tutorial or class to ask these but there's too many things to do and this assignment has already taken me way to long due to the setup…):

Is this process correct? If not what should I change?

What should be the output I expect, where should the images be found?

**Comment by MicheleMassa802** [comment]
Also if any other classmates who are using windows have gotten their project to work and gotten an output, please feel free to reply with the steps that you followed to get an output, I really be struggling here

**Comment by kevin-j-wang** [comment]
![image](https://user-images.githubusercontent.com/56416268/190920965-b28f1d93-bbb6-4d56-8cc5-a4042bdd63d6.png)
if you see this after opening the .sln with visual studio, you should set raster as your startup project by right clicking it, and then run local windows debugger, not on ALL_BUILD. at least, that was what worked for me.

**Comment by MicheleMassa802** [comment]
> ![image](https://user-images.githubusercontent.com/56416268/190920965-b28f1d93-bbb6-4d56-8cc5-a4042bdd63d6.png) if you see this after opening the .sln with visual studio, you should set raster as your startup project by right clicking it, and then run local windows debugger, not on ALL_BUILD. at least, that was what worked for me.

It seems to be running that way, there are a couple errors but it just seems like unhandled exceptions from my end, thank you very much for your help :)
