### ISSUE TITLE
Can't read from png

### ISSUE THREAD

**Issue by yi1z** [karansher/computer-graphics-raster-images#57]
All my ppm files appear to be 0kb, and so I checked the size of the rgba returned by the function read_rgba_from_png and it appears to be 0, can someone help me with this I've spent hours on this problem
![image](https://user-images.githubusercontent.com/90294263/190929967-27b11a8c-ce09-4f1a-acb7-194d5f6fdd20.png)

**Comment by yi1z** [comment]
Also the width and height appear to be weird as well
![image](https://user-images.githubusercontent.com/90294263/190930048-b779bb08-385b-4969-b7f7-5bd6a129f780.png)

**Comment by abhimadan** [comment]
This is the same issue several other students have encountered where their executable isn't being run from the correct place. Carefully read the FAQ on the github readme for this assignment, and also take a look at past issues (both open and closed) in this repo for more detailed explanations. From your screenshots, I strongly suspect you just opened the project without running `cmake ..` from the command line, so you need to delete the contents of your `build` folder and run `cmake ..` from there.

**Comment by yi1z** [comment]
Thank you I've solved the problem!
