### ISSUE TITLE
rgb yellowish dog

### ISSUE THREAD

**Issue by cccccz** [karansher/computer-graphics-raster-images#58]
![image](https://user-images.githubusercontent.com/60713799/190934266-b179c682-4a80-4638-b5c9-82971fb81641.png)
This is my output for rgb.ppm. It looks too yellow to me but I have no clue how to fix it...

**Comment by abhimadan** [comment]
In `rgba_to_rgb`, you just drop the alpha channel when copying to the output buffer. To find out what's going on here, try using a debugger to see what values you copy to the output buffer, or print out each RGBA pixel and compare it with your ppm file read as a text file.

**Comment by cccccz** [comment]
> In `rgba_to_rgb`, you just drop the alpha channel when copying to the output buffer. To find out what's going on here, try using a debugger to see what values you copy to the output buffer, or print out each RGBA pixel and compare it with your ppm file read as a text file.

Thank you for the reply! I see that in my ppm file, the blue value is always 0, i think that's where the problem came from.
