### ISSUE TITLE
My image dimensions are zero after I reinstalled the cmake

### ISSUE THREAD

**Issue by CaulesGe** [karansher/computer-graphics-raster-images#62]
I have finished some tasks and their outputs are successful. However, when I finished the hue_shift.cpp it raised error, so I deleted the build folder and reinstalled cmake. I also cloned a new repository and pasted my original src folder to it. However, when I run the main.cpp through the raster.sln in the build folder, all image dimensions are zero. How can I fix it?

**Comment by abhimadan** [comment]
I don't really understand your question. Can you clarify the following points:
- What error did you get from hue_shift?
- Did you reinstall cmake or rerun `cmake ..` from the new build folder?
- Why did you clone a new repository?
- Did you open raster.sln or did you open your project folder?

**Comment by CaulesGe** [comment]
nvm, I have fixed it. Thx!
