### ISSUE TITLE
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

### ISSUE THREAD

**Issue by ValentinaManferrari** [karansher/computer-graphics-raster-images#64]
![image](https://user-images.githubusercontent.com/57778780/191085418-3bd58311-07d9-4806-b273-1ae1c888c1ab.png)

Hey! Is anyone able to tell me what is going on here? Cmake is downloaded and added to $PATH, I am using vscode and the cmake extensions are also there... thanks in advance

**Comment by ValentinaManferrari** [comment]
https://stackoverflow.com/questions/70524164/cmake-c-compiler-not-set-after-enablelanguage
I saw this but I also am not able to find the path to g++ or gcc... they are not in .\Program Files\Cmake \

**Comment by abhimadan** [comment]
You need to install Visual Studio, not VSCode. Despite the similar names, they're two different things, where one is an IDE that includes a compiler, while VSCode is just a text editor.

**Comment by ValentinaManferrari** [comment]
Oooh ok, thank you! Which workload(s) do you recommend downloading for these labs? Is the one in the below screenshot ok? I could not find any specifications in the lab instructions... 
![image](https://user-images.githubusercontent.com/57778780/191096787-5b3fd107-bdda-48ce-b51b-aee17de1dcc8.png)

**Comment by abhimadan** [comment]
At the bottom of the page https://github.com/karansher/computer-graphics-raster-images, we say to install the "Desktop Development for C++" workload.
