### ISSUE TITLE
demosaic.cpp

### ISSUE THREAD

**Issue by HELENCUICUI** [karansher/computer-graphics-raster-images#65]
Can someone give some hint on why mine demosaic.ppm look like this? 
<img width="386" alt="Screen Shot 2022-09-19 at 4 11 35 PM" src="https://user-images.githubusercontent.com/113476839/191107807-a197e314-45e6-427c-93a4-c7d674f64cb4.png">

**Comment by abhimadan** [comment]
It's difficult to tell, since there are a variety of places where you can introduce bugs. One common case is related to doing integer division (e.g., between two unsigned chars) when you really need to divide two floats.

**Comment by HELENCUICUI** [comment]
Thanks! I tried that. But I still got the same colour image.Is there a reason why the particular colour of the image? Am I missing anything in the interpolation calculation that leads to this colours? I have no clue what I might have done wrong. 
<img width="386" alt="Screen Shot 2022-09-19 at 11 57 04 PM" src="https://user-images.githubusercontent.com/113476839/191164185-3a624e22-760a-4915-a0ba-1ae4c426fb36.png">

**Comment by Tahmeem** [comment]
did you figure this out? I'm getting a similar image using the stuff that was taught in lecture.
