### ISSUE TITLE
Vector subscript out of range

### ISSUE THREAD

**Issue by ValentinaManferrari** [karansher/computer-graphics-raster-images#75]
![image](https://user-images.githubusercontent.com/57778780/191290966-ac52189a-0480-4f5e-9207-a885dc3949b5.png)
Hello! I have written the rgba_to_rgb and write_ppm functions and I am getting this error every time I try to run the program... I checked all vectors and I am not accessing any out-of-bound vector index, do you know if the error could be caused by another file? I was trying to find logs to see the exact line where the error is occurring but I cannot find anything in the debug mode... any debugging tip/suggestion? Thank you so much in advance

**Comment by ValentinaManferrari** [comment]
Nevermind sorry I fixed it

**Comment by scissorkhizer** [comment]
I ended up encountering the same issue and don't think I'm accessing an out of bound index. Can you share what exactly went wrong (if that's okay to share ofcourse)? 

Edit: Nevermind, I also fixed it lol
