### ISSUE TITLE
Regarding the data vector that we are using

### ISSUE THREAD

**Issue by sean-seowon-yi** [karansher/computer-graphics-raster-images#77]
Hello, for write_ppm.cpp I believe the data vector we are using cannot be used directly (that is, they are not integers). Thus, we need to convert them somehow.

When I cast them directly to the integer, I end up getting all 0, so I believe there have to be more steps to be done.

Could there be a little hint?

Thank you!

**Comment by abhimadan** [comment]
Casting from unsigned char to int is all that needs to be done, so you likely have some other issue.

**Comment by OneAutumnRain** [comment]
Have the same issue. Debugger shows cast from unsigned char to int went through, but still only 0 written.

**Comment by sean-seowon-yi** [comment]
I fixed it by changing rgba to rgb function.
Hope this helps xD
