### ISSUE TITLE
Can't open file when trying to run raster.exe?

### ISSUE THREAD

**Issue by andyw1589** [karansher/computer-graphics-raster-images#9]
I'm trying to run raster.exe from the command line like the FAQ said, but I get this: 
![image](https://user-images.githubusercontent.com/46545759/190029993-e12b5490-0f05-45f5-8d96-28a24c65f5b7.png)

**Comment by andyw1589** [comment]
wait a minute, i forgot that the error message is something that i added myself 💀💀💀💀

but it still can't open the image files regardless

**Comment by abhimadan** [comment]
Where did you add this error message?

**Comment by andyw1589** [comment]
nevermind, i realized that the error message is for something i didn't actually implement yet 💀
